services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: username # The PostgreSQL user
      POSTGRES_PASSWORD: password # The PostgreSQL password
      POSTGRES_DB: portfoliocms # The PostgreSQL default database

networks:
  postgres-network:
    driver: bridge
